sudo: false

language: go

services:
  - docker

go:
  - 1.8

env:
  - DOCKER_IMAGE=pragkent/slackwork:0.2.0

script:
  - set -e
  - go get -t ./...
  - make test
  - make static
  - docker build -t $DOCKER_IMAGE .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $DOCKER_IMAGE
